<?php

/**
 * Copyright Elgentos BV. All rights reserved.
 * https://www.elgentos.nl/
 */

declare(strict_types=1);

use Elgentos\StoreSwitcher\ViewModel\StoreSwitcher;
use Hyva\Theme\Model\ViewModelRegistry;
use Hyva\Theme\ViewModel\SvgIcons;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;
use Magento\Store\ViewModel\SwitcherUrlProvider;

/** @var Template $block */
/** @var Escaper $escaper */
/** @var ViewModelRegistry $viewModels */
/** @var SvgIcons $icons */
/** @var SwitcherUrlProvider $switcherUrlProvider */

$switcherUrlProvider = $viewModels->require(SwitcherUrlProvider::class);
$icons               = $viewModels->require(SvgIcons::class);
$storeSwitcher       = $viewModels->require(StoreSwitcher::class);
$currentStore        = $storeSwitcher->getCurrentStore();
$availableStores     = $storeSwitcher->getStores($currentStore->getCode());
?>
<div
    x-data="{open: false}"
    @click.outside="open = false"
    @keyup.escape="open = false"
    class="relative"
>
    <button
        type="button"
        title="<?= $escaper->escapeHtmlAttr($currentStore->getName()) ?>"
        @click="open = !open"
        class="rounded hover:bg-indigo-100 p-1 h-8 min-w-8 flex items-center justify-center outline-offset-2"
    >
        <?= /* @noEscape */ $storeSwitcher->getLabelRenderer()->render($currentStore)?>
    </button>
    <div
        x-show="open"
        x-cloak
        class="
            absolute right-0 z-20 w-40 py-2 mt-2 -mr-4 px-1 overflow-auto origin-top-right rounded-sm
            shadow-lg sm:w-48 lg:mt-3 bg-container-lighter
        "
    >
        <ul>
            <li class="block">
                <?php foreach ($availableStores as $store): ?>
                <a
                    href="<?= $escaper->escapeUrl($switcherUrlProvider->getTargetStoreRedirectUrl($store)) ?>"
                    rel="nofollow"
                    class="block px-4 py-2 lg:px-5 lg:py-2 hover:bg-gray-100"
                >
                    <?= $escaper->escapeHtml($store->getName()) ?>
                </a>
                <?php endforeach; ?>
            </li>
        </ul>
    </div>
</div>
